// Proposed pilot data for the shareable demonstration. No campaign is live.
export const plan = {
  title: "Nightbird, introduced properly.",
  subtitle: "A proposed 30-day creator pilot · Ready to shape together",
  objective: "Test which expression of Nightbird earns meaningful interest from an adult audience, then use that evidence to decide the next investment.",
  product: {
    name: "Nightbird Vodka",
    abv: "40% alc/vol",
    volume: "700 mL",
    image: "/assets/nightbird-detail.webp",
  },
  phases: [
    {
      id: "align",
      week: "Week 1 · Days 1–7",
      title: "Set the direction",
      summary: "Agree what success means, confirm the product and choose the right creative partners.",
      deliverables: [
        "Matt and Tim approve one objective, an audience and a spending ceiling.",
        "Confirm available stock, sample bottles, shipping costs and packaging.",
        "Review three creator slots against audience fit, work quality and rights.",
        "Approve the three creative treatments and the measurement plan.",
      ],
    },
    {
      id: "make",
      week: "Week 2 · Days 8–14",
      title: "Make the first stories",
      summary: "Turn the approved direction into a small, considered body of content.",
      deliverables: [
        "Agree creator contracts, usage permissions and sample delivery before production.",
        "Produce three vertical first cuts, each with an alternate opening.",
        "Review scripts, captions and product accuracy alongside the footage.",
        "Connect and test the adult launch-interest journey before any live traffic.",
      ],
    },
    {
      id: "release",
      week: "Week 3 · Days 15–21",
      title: "Release with intention",
      summary: "Publish only after approval, then compare creative on a consistent basis.",
      deliverables: [
        "Record final brand approval, usage rights and content/placement review.",
        "Publish approved work to the agreed channels with a unique tracked link per concept.",
        "If budget is approved, test the three concepts with comparable placement and spend.",
        "Review traffic quality and feedback; record observations without declaring an early winner.",
      ],
    },
    {
      id: "learn",
      week: "Week 4 · Days 22–30",
      title: "Learn, then decide",
      summary: "Give Matt a useful decision, supported by what the pilot actually taught us.",
      deliverables: [
        "Compare attention, landing-page visits and qualified interest by creative.",
        "Reconcile the actual spend and document the limits of the sample.",
        "Identify one creative to refine, one assumption to retest and one thing to stop.",
        "Agree whether to extend Nightbird, prepare commerce or pause for more evidence.",
      ],
    },
  ],
  creators: [
    {
      id: "creator-design",
      name: "Creator slot 01",
      specialism: "Design & detail",
      brief: "An adult product storyteller with a restrained visual style. Make the glass, gold geometry and bird signature the subject.",
      deliverables: ["One 20-second vertical film", "One alternate opening", "Three selected still frames"],
      fee: null,
      status: "shortlist",
      audience: "To verify",
      rights: "To agree",
    },
    {
      id: "creator-hosting",
      name: "Creator slot 02",
      specialism: "Considered hosting",
      brief: "An adult interiors or hosting creator. Show a beautifully prepared table with food, water and considered details; Nightbird is one element in the setting.",
      deliverables: ["One 25-second vertical film", "One alternate opening", "Three selected still frames"],
      fee: null,
      status: "shortlist",
      audience: "To verify",
      rights: "To agree",
    },
    {
      id: "creator-craft",
      name: "Creator slot 03",
      specialism: "Cocktail craft",
      brief: "An adult bartender or drinks educator. Focus on measured preparation, glassware and a simple serve, using a recipe approved by Matt before filming.",
      deliverables: ["One 30-second vertical film", "One alternate opening", "Three selected still frames"],
      fee: null,
      status: "shortlist",
      audience: "To verify",
      rights: "To agree",
    },
  ],
  content: [
    {
      id: "gold-in-the-detail",
      title: "The gold is in the detail",
      format: "Vertical film · 9:16",
      duration: "20 seconds",
      angle: "Design-led product discovery",
      image: "/assets/nightbird-detail.webp",
      hook: "A bird. A line. A different perspective.",
      shots: [
        "00–04s · A narrow band of light reveals the gold bird on the bottle.",
        "04–08s · Move slowly across the geometric detailing; keep the real label legible.",
        "08–14s · Show the faceted stopper and clear glass in a quiet studio setting.",
        "14–20s · Hold on the complete bottle. Nightbird wordmark and discovery link.",
      ],
      script: "A bird in flight. Gold lines. Clear glass. Some things are worth a closer look. Meet Nightbird Vodka.",
      caption: "A closer look at Nightbird. Clear glass, gold geometry and a signature in flight. Discover the bottle. 18+ · Enjoy responsibly.",
      cta: "Discover Nightbird",
      checks: [
        "Match the supplied bottle artwork and confirmed 40% alc/vol, 700 mL details.",
        "Avoid unverified origin, distillation, flavour, award or quality claims.",
        "Confirm creator eligibility, usage permissions and approved adult placement before release.",
      ],
      status: "concept",
    },
    {
      id: "a-considered-table",
      title: "A considered table",
      format: "Vertical film · 9:16",
      duration: "25 seconds",
      angle: "Quiet hosting & visual atmosphere",
      image: "/assets/nightbird-campaign.webp",
      hook: "The table, in five details.",
      shots: [
        "00–05s · Linen laid on a table, followed by a close-up of the glassware.",
        "05–10s · Place food and a carafe of water; warm light stays natural.",
        "10–16s · Place Nightbird beside the glassware and linger on the gold detailing.",
        "16–21s · Reveal the finished table without drinking, a toast or a social transformation.",
        "21–25s · Bottle detail and a quiet end frame linking to Nightbird.",
      ],
      script: "Linen. Glass. Something to share at the table. Water within reach. And a little gold in the detail. Nightbird Vodka.",
      caption: "A table study in texture, glass and gold. Featuring Nightbird Vodka. Explore the details. 18+ · Enjoy responsibly.",
      cta: "Explore the Nightbird world",
      checks: [
        "Show an adult setting with food and water; no suggestion alcohol creates friendship or a better evening.",
        "Any visible talent must meet the applicable ABAC age requirements.",
        "Approve the complete footage, caption, disclosure and placement together.",
      ],
      status: "concept",
    },
    {
      id: "the-considered-serve",
      title: "The considered serve",
      format: "Vertical film · 9:16",
      duration: "30 seconds",
      angle: "Bartender craft & measured preparation",
      image: "/assets/nightbird-campaign-mobile.webp",
      hook: "Good preparation starts with a measure.",
      shots: [
        "00–05s · An adult bartender sets a jigger beside a chilled glass.",
        "05–12s · Measure the serve according to the recipe Matt has approved.",
        "12–20s · Add ice and the approved mixer; show the preparation in clear close-ups.",
        "20–25s · Stir gently and add the agreed garnish. Keep water in the setting.",
        "25–30s · Finished serve and Nightbird bottle. End on the product discovery link.",
      ],
      script: "A chilled glass. Fresh ice. A measured pour. Your chosen mixer. Keep the preparation simple and let the details speak. Nightbird Vodka.",
      caption: "A measured approach to the Nightbird serve. Recipe and quantities to be approved before filming. Discover Nightbird. 18+ · Enjoy responsibly.",
      cta: "Discover the Nightbird serve",
      checks: [
        "Approve the actual recipe, serving quantities and preparation before production.",
        "Use a measured pour; no rapid consumption, intoxication or health/performance claims.",
        "Final caption must replace the draft recipe note before publication.",
      ],
      status: "concept",
    },
  ],
  goals: [
    {
      id: "goal-objective",
      title: "Agree the pilot objective",
      detail: "Choose the adult audience, priority channel and decision this pilot must inform. Set the target together once cost and reach assumptions are known.",
      owner: "Matt + Tim",
      due: "Week 1",
      phase: "readiness",
      target: "One approved brief and decision rule",
      evidence: "Written approval of objective, audience, target and spending ceiling",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-product",
      title: "Confirm product and sample stock",
      detail: "Confirm the current bottle, available units, sample allocation and only the claims Matt can substantiate. Retail availability is still unconfirmed.",
      owner: "Matt",
      due: "Week 1",
      phase: "readiness",
      target: "One verified product sheet and sample allocation",
      evidence: "Approved artwork, product facts and stock confirmation",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-shipping",
      title: "Make single-bottle shipping viable",
      detail: "Confirm protective packaging, freight quotes, service area, breakage handling and the contribution remaining after fulfilment. Do not promise delivery or open orders yet.",
      owner: "Matt + fulfilment partner",
      due: "Week 1",
      phase: "readiness",
      target: "One tested pack and documented unit-economics estimate",
      evidence: "Pack test, freight quote and cost worksheet",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-creators",
      title: "Select the three creative partners",
      detail: "Replace the three placeholder slots with reviewed candidates. Confirm age eligibility, adult audience, relevant work and a quoted scope before selection.",
      owner: "Tim; Matt approves",
      due: "Week 1",
      phase: "readiness",
      target: "Three reviewed candidates; final scope approved",
      evidence: "Portfolio, audience evidence, quoted fee and selection decision",
      status: "todo",
      critical: false,
    },
    {
      id: "goal-rights",
      title: "Agree rights before production",
      detail: "Document deliverables, revisions, organic and paid usage, term, territory, music and talent permissions. Agree any creator-account advertising separately.",
      owner: "Tim + selected creators; Matt approves",
      due: "Week 2",
      phase: "production",
      target: "Written agreement for every commissioned creator",
      evidence: "Agreed scope, fees, usage permissions and sample receipt",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-first-cuts",
      title: "Create three distinct first cuts",
      detail: "Develop the design, hosting and craft concepts. Each proposed creator supplies a main vertical film and one alternate opening; these are proposed outputs, not commissioned work.",
      owner: "Selected creators; Tim coordinates",
      due: "Week 2",
      phase: "production",
      target: "Three first cuts and three alternate openings",
      evidence: "Actual review files, scripts and draft captions",
      status: "todo",
      critical: false,
    },
    {
      id: "goal-interest-flow",
      title: "Connect the launch-interest journey",
      detail: "Blocked until a real adult interest form, privacy notice, consent handling and record destination are implemented and tested. The public site currently accepts no enquiries or orders.",
      owner: "Tim; Matt approves purpose and follow-up",
      due: "Before Week 3",
      phase: "readiness",
      target: "One tested journey from creative link to valid consented record",
      evidence: "End-to-end test, approved privacy copy and confirmed data destination",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-measurement",
      title: "Prove the measurement works",
      detail: "Define a qualified-interest record, exclude tests and duplicates, assign a unique campaign link to each concept and validate attribution before driving traffic.",
      owner: "Tim",
      due: "Before Week 3",
      phase: "learning",
      target: "Every proposed concept has a tested link and event path",
      evidence: "Test records, event definitions and source-to-landing checks",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-release-approval",
      title: "Approve the complete release",
      detail: "Review the finished content, claims, disclosure, rights and adult audience/placement against current ABAC and platform requirements. Matt signs off before any publishing or paid spend.",
      owner: "Tim prepares; Matt approves",
      due: "Before Week 3",
      phase: "production",
      target: "Approval recorded for each asset and placement",
      evidence: "Final creative, caption, placement settings and approval record",
      status: "todo",
      critical: true,
    },
    {
      id: "goal-publish",
      title: "Run a fair creative test",
      detail: "Release approved work only when the launch gates are met. Keep the audience, format, placement and observation period comparable; log any differences.",
      owner: "Tim + approved publishing partners",
      due: "Week 3",
      phase: "learning",
      target: "Three comparable creative observations within the approved budget",
      evidence: "Live URLs, publishing dates, placement details and actual spend",
      status: "todo",
      critical: false,
    },
    {
      id: "goal-learnings",
      title: "Turn performance into a next action",
      detail: "Compare creative attention, visits and qualified interest only after enough evidence is available. Record weak attribution or a small sample as limitations.",
      owner: "Tim",
      due: "Week 4",
      phase: "learning",
      target: "One evidence-backed recommendation per concept",
      evidence: "Source exports, spend reconciliation and short findings note",
      status: "todo",
      critical: false,
    },
    {
      id: "goal-next-step",
      title: "Decide the next investment together",
      detail: "Review the pilot against the agreed decision rule. Extend, refine or pause. Plan a sales test only after checkout, fulfilment and contribution economics are ready.",
      owner: "Matt + Tim",
      due: "Day 30",
      phase: "learning",
      target: "One recorded decision with an owner and next milestone",
      evidence: "Pilot review and approved next-stage scope",
      status: "todo",
      critical: false,
    },
  ],
  budget: [
    { id: "content", label: "Creator production", description: "Quoted content fees, agreed revisions and usage rights. No creators are booked." },
    { id: "media", label: "Paid media", description: "Optional test spend, released only after Matt approves budget, assets and placement." },
    { id: "samples", label: "Samples & freight", description: "Product allocation, protective packaging, sample delivery and any agreed returns." },
    { id: "experience", label: "Landing & measurement", description: "Campaign landing improvements, real interest capture, consent, tracking and reporting setup." },
    { id: "contingency", label: "Contingency", description: "An explicitly agreed reserve for reshoots, replacement samples or other approved changes." },
  ],
  metrics: [
    { id: "attention", label: "Creative attention", description: "Compare early viewing and completion using each platform’s definitions. Keep formats and placements comparable.", source: "Creator or advertising platform reports", availability: "Not connected · No content published" },
    { id: "visits", label: "Qualified landing visits", description: "Visits to the Nightbird page by creative source, with agreed filters for test and invalid traffic.", source: "Consented site analytics + campaign links", availability: "Not connected · Tracking to implement" },
    { id: "interest", label: "Qualified launch interest", description: "Unique adult, consented, non-test records that match the agreed service area and interest definition.", source: "Approved interest form + record destination", availability: "Blocked · Capture flow not connected" },
    { id: "cost-interest", label: "Cost per qualified interest", description: "Report both media spend per valid interest record and total pilot cost per valid record. No ratio until real costs and valid records exist.", source: "Reconciled spend + qualified interest records", availability: "Unavailable until spend and capture are connected" },
    { id: "feedback", label: "Audience response", description: "Summarise useful questions and product interest without treating likes or comments as purchase intent.", source: "Approved channel comments + consented enquiries", availability: "No live responses" },
    { id: "commercial", label: "Sales & contribution", description: "A future commerce measure: order revenue less product, fulfilment, fees and acquisition costs using agreed definitions.", source: "Future order and cost systems", availability: "Not available · Ecommerce is not enabled" },
  ],
  decisions: [
    { id: "decision-brand", title: "Choose the parent-brand direction", detail: "Review the premium naming shortlist and confirm the working direction before changing the public identity. Names still need formal clearance.", owner: "Matt + Tim" },
    { id: "decision-objective", title: "Agree what this pilot must prove", detail: "Choose the adult audience, definition of qualified interest and the evidence needed for another investment.", owner: "Matt + Tim" },
    { id: "decision-budget", title: "Set a spending ceiling", detail: "Enter provisional estimates, request actual quotes and approve the total before any commitments.", owner: "Matt" },
    { id: "decision-start", title: "Choose a realistic start date", detail: "The four weeks are relative. Set a start only after stock, samples and creator availability have been confirmed.", owner: "Matt + Tim" },
    { id: "decision-capture", title: "Approve the interest-capture purpose", detail: "Decide what adults are signing up for, who follows up and where records will be stored before collecting any personal information.", owner: "Matt + Tim" },
  ],
  sources: [
    { label: "ABAC responsible digital marketing guidance", url: "https://www.abac.org.au/wp-content/uploads/2025/06/Best-Practice-for-Responsible-Digital-Marketing-4-6-25.pdf" },
    { label: "ABAC Code and review process", url: "https://abac.org.au/about/thecode/" },
  ],
  roles: [
    { name: "Matt · Product & final approval", responsibilities: "Confirm product facts, stock, fulfilment and costs; approve budgets, creative and the decision to proceed. Proposed role, to agree together." },
    { name: "Tim · Brand & campaign coordination", responsibilities: "Shape the experience, coordinate briefs and reviews, prepare measurement and report useful next actions. Proposed scope, subject to an agreed engagement." },
    { name: "Selected creators · Content production", responsibilities: "Produce the agreed assets, supply audience evidence and permissions, and follow the approved brief. No creators have been selected or booked." },
  ],
};
